apiVersion: v1
kind: Namespace
metadata:
  name: hogyoku
  labels:
    app.kubernetes.io/part-of: hogyoku
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: raft
  namespace: hogyoku
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway
  namespace: hogyoku
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workload-no-api-access
  namespace: hogyoku
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workload-no-api-access
  namespace: hogyoku
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workload-no-api-access
subjects:
  - kind: ServiceAccount
    name: raft
    namespace: hogyoku
  - kind: ServiceAccount
    name: api-gateway
    namespace: hogyoku
