apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-namespace-rbac.yaml
  - 10-configmap.yaml
  - 20-services.yaml
  - 30-raft-statefulset.yaml
  - 40-api-gateway.yaml
  - 50-network-policy.yaml
